

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo k8s terraform Azure!
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$()'
    backendType: 'azurerm'
    backendServiceArm: 'azure'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctirbairmeen'
    backendAzureRmContainerName: 'storageacctirbairmeencontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
  displayName: 'Run a one-line script'

